version: "3.8"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    volumes:
      - souq_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U odoo"]
      interval: 5s
      timeout: 5s
      retries: 10

  odoo:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8069:8069"
    environment:
      HOST: db
      USER: odoo
      PASSWORD: odoo
    volumes:
      - ../souq:/mnt/extra-addons/souq
      - souq_odoo_data:/var/lib/odoo
      - ./odoo.conf:/etc/odoo/odoo.conf
    command: >
      odoo -c /etc/odoo/odoo.conf -i souq --dev=all

volumes:
  souq_db_data:
  souq_odoo_data:
