from . import souq_branch
from . import sale_order
from . import account_move
from . import souq_cod_collection
from . import souq_driver_settlement
from . import souq_driver_float
from . import stock_picking
from . import souq_einvoice
from . import res_config_settings
from . import res_partner
from . import souq_branch_transfer
